submodules:
  - client

services:
  - type: web
    name: lumireads-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: lumireads-backend-disk
      mountPath: /app
      sizeGB: 1

  - type: web
    name: lumireads-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 14
      - key: REACT_APP_API_URL
        value: https://lumireads-backend.onrender.com
    autoDeploy: true
    staticPublishPath: client/build
    healthCheckPath: /
    disk:
      name: lumireads-frontend-disk
      mountPath: /app
      sizeGB: 1
